/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description The SPA's login signal: 401 here means "send the visitor to /accounts/login/".
         */
        get: operations["read_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me"];
        trace?: never;
    };
    "/api/me/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Photo */
        put: operations["upload_photo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites"];
        /** Save Favorites */
        put: operations["save_favorites"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Books */
        get: operations["search_books"];
        put?: never;
        /**
         * Create Book
         * @description Idempotent on (title, author): the same book coming twice from the
         *     autocomplete must not blow up on the unique constraint.
         */
        post: operations["create_book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search External Books */
        get: operations["search_external_books"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Book */
        get: operations["read_book"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Picks */
        get: operations["list_picks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Pick */
        get: operations["current_pick"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current/readers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Readers */
        get: operations["current_readers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Reading */
        get: operations["my_reading"];
        /** Update Reading */
        put: operations["update_reading"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts"];
        put?: never;
        /** Create Post */
        post: operations["create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Post */
        get: operations["read_post"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post"];
        options?: never;
        head?: never;
        /** Update Post */
        patch: operations["update_post"];
        trace?: never;
    };
    "/api/posts/{post_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Image */
        post: operations["attach_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookOut */
        BookOut: {
            /** Cover Image */
            cover_image: string;
            /** ID */
            id?: number | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year?: number | null;
            /** Pages */
            pages?: number | null;
            /** Synopsis */
            synopsis?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
            /** Quote */
            quote: string;
            /** Birth Date */
            birth_date: string | null;
            /** Favorites */
            favorites: components["schemas"]["BookOut"][];
        };
        /** ProfileInPatch */
        ProfileInPatch: {
            /** Full Name */
            full_name?: string | null;
            /** Quote */
            quote?: string | null;
            /** Birth Date */
            birth_date?: string | null;
        };
        /** FavoriteIn */
        FavoriteIn: {
            /** Book Id */
            book_id: number;
            /** Position */
            position: number;
        };
        /** FavoritesIn */
        FavoritesIn: {
            /** Favorites */
            favorites: components["schemas"]["FavoriteIn"][];
        };
        /** UserBrief */
        UserBrief: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
        };
        /** MonthlyPickOut */
        MonthlyPickOut: {
            /** Id */
            id: number;
            /**
             * Month
             * Format: date
             */
            month: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Blurb */
            blurb: string;
            book: components["schemas"]["BookOut"];
        };
        /**
         * ReadingHistoryOut
         * @description A past reading as it appears on a profile — it carries its own pick.
         */
        ReadingHistoryOut: {
            /** Pages Read */
            pages_read: number;
            /** Percent */
            percent: number | null;
            /** Rating */
            rating: number | null;
            /** Review */
            review: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            pick: components["schemas"]["MonthlyPickOut"];
        };
        /** UserProfileOut */
        UserProfileOut: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
            /** Quote */
            quote: string;
            /** Birth Date */
            birth_date: string | null;
            /** Favorites */
            favorites: components["schemas"]["BookOut"][];
            /** Readings */
            readings: components["schemas"]["ReadingHistoryOut"][];
        };
        /** BookIn */
        BookIn: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year?: number | null;
            /** Pages */
            pages?: number | null;
            /**
             * Synopsis
             * @default
             */
            synopsis: string;
            /**
             * Cover Url
             * @default
             */
            cover_url: string;
            /**
             * External Id
             * @default
             */
            external_id: string;
        };
        /**
         * ExternalBookOut
         * @description A hit from the external catalogue, shaped so it can be POSTed back as a BookIn.
         */
        ExternalBookOut: {
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year: number | null;
            /** Pages */
            pages: number | null;
            /** Cover Url */
            cover_url: string;
        };
        /**
         * ReaderOut
         * @description One member's position in the current pick, for the "who is reading" list.
         */
        ReaderOut: {
            user: components["schemas"]["UserBrief"];
            /** Pages Read */
            pages_read: number;
            /** Percent */
            percent: number | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** MonthlyReadingOut */
        MonthlyReadingOut: {
            /** Pages Read */
            pages_read: number;
            /** Percent */
            percent: number | null;
            /** Rating */
            rating: number | null;
            /** Review */
            review: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MonthlyReadingIn */
        MonthlyReadingIn: {
            /** Pages Read */
            pages_read?: number | null;
            /** Rating */
            rating?: number | null;
            /** Review */
            review?: string | null;
        };
        /** Page */
        Page: {
            /** Items */
            items: components["schemas"]["PostOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Has Next */
            has_next: boolean;
        };
        /** PostOut */
        PostOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            author: components["schemas"]["UserBrief"];
            book: components["schemas"]["BookOut"] | null;
            /** Images */
            images: string[];
        };
        /** PostIn */
        PostIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Book Id */
            book_id?: number | null;
        };
        /** PostInPatch */
        PostInPatch: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Book Id */
            book_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    upload_photo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    save_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoritesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    search_users: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBrief"][];
                };
            };
        };
    };
    read_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
        };
    };
    search_books: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    create_book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
        };
    };
    search_external_books: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalBookOut"][];
                };
            };
        };
    };
    read_book: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
        };
    };
    list_picks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPickOut"][];
                };
            };
        };
    };
    current_pick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPickOut"];
                };
            };
        };
    };
    current_readers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderOut"][];
                };
            };
        };
    };
    my_reading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReadingOut"];
                };
            };
        };
    };
    update_reading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyReadingIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReadingOut"];
                };
            };
        };
    };
    list_posts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    attach_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
}
