/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description The SPA's login signal: 401 here means "send the visitor to /accounts/login/".
         */
        get: operations["read_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me"];
        trace?: never;
    };
    "/api/me/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Photo */
        put: operations["upload_photo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites"];
        /** Save Favorites */
        put: operations["save_favorites"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Books */
        get: operations["search_books"];
        put?: never;
        /**
         * Create Book
         * @description Idempotent on (title, author): the same book coming twice from the
         *     autocomplete must not blow up on the unique constraint.
         */
        post: operations["create_book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search External Books */
        get: operations["search_external_books"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Book */
        get: operations["read_book"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Picks */
        get: operations["list_picks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Pick */
        get: operations["current_pick"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current/readers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finished Readers
         * @description Who has finished this month's book and left a rating.
         *
         *     Both halves of the filter are load-bearing. `finished_at` is what makes this "quem já
         *     terminou" instead of "quem está lendo", and `rating_halves__isnull=False` is what gives
         *     every row something to say. **A rating of 0 keeps a member on this list**: zero stars is an
         *     opinion, and the only way a reading has no rating at all is for nobody to have written one
         *     — the column is `null=True` with no default, so it is born NULL and a 0 only ever arrives
         *     because someone sent one. Erasing a rating (`MonthlyReadingIn.clear_rating`) takes the row
         *     back off the list, which is the reversibility DESIGN.md 9 asks for.
         *
         *     Ordered by name, not by when they finished or by how far they read: this is companionship,
         *     not a race (DESIGN.md 9). `pick__book` left the select_related along with `percent` — the
         *     only relation this response reads now is `user`, and that one is still the difference
         *     between one query and N.
         */
        get: operations["finished_readers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monthly-picks/current/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Reading */
        get: operations["my_reading"];
        /** Update Reading */
        put: operations["update_reading"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts"];
        put?: never;
        /** Create Post */
        post: operations["create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unread Posts
         * @description The number behind the badge on the balão in the header.
         */
        get: operations["unread_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Posts Seen
         * @description Opening the feed is what marks the postagens as read — there is no per-post state.
         *
         *     One stamp on the member, not a row per post: what the badge has to answer is "is there
         *     anything new since you last looked", and a timestamp answers exactly that. Per-post read
         *     receipts would be a table that grows with members × postagens to tell us nothing more.
         */
        post: operations["mark_posts_seen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Post */
        get: operations["read_post"];
        put?: never;
        post?: never;
        /** Delete Post */
        delete: operations["delete_post"];
        options?: never;
        head?: never;
        /** Update Post */
        patch: operations["update_post"];
        trace?: never;
    };
    "/api/posts/{post_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Image */
        post: operations["attach_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BookOut */
        BookOut: {
            /** Cover Image */
            cover_image: string;
            /** ID */
            id?: number | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year?: number | null;
            /** Pages */
            pages?: number | null;
            /** Synopsis */
            synopsis?: string | null;
        };
        /**
         * MeOut
         * @description `GET /api/me` — the member as *they* see themselves.
         *
         *     `is_staff` is here rather than in `UserBrief` or `UserOut` on purpose. It is the flag the
         *     SPA reads to decide whether to draw the "Postar" shortcuts, and it is nobody else's
         *     business: `UserProfileOut` extends `UserOut` too, so a field added there would have shown
         *     up on every public profile. Putting it in the shared projection would have been worse
         *     still — a projection is project-wide vocabulary (ADR-15, rule 3).
         */
        MeOut: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
            /** Quote */
            quote: string;
            /** Birth Date */
            birth_date: string | null;
            /** Favorites */
            favorites: components["schemas"]["BookOut"][];
            /** Is Staff */
            is_staff: boolean;
        };
        /** ProfileInPatch */
        ProfileInPatch: {
            /** Full Name */
            full_name?: string | null;
            /** Quote */
            quote?: string | null;
            /** Birth Date */
            birth_date?: string | null;
        };
        /** FavoriteIn */
        FavoriteIn: {
            /** Book Id */
            book_id: number;
            /** Position */
            position: number;
        };
        /** FavoritesIn */
        FavoritesIn: {
            /** Favorites */
            favorites: components["schemas"]["FavoriteIn"][];
        };
        /** UserBrief */
        UserBrief: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
        };
        /** MonthlyPickOut */
        MonthlyPickOut: {
            /** Id */
            id: number;
            /**
             * Month
             * Format: date
             */
            month: string;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Blurb */
            blurb: string;
            book: components["schemas"]["BookOut"];
        };
        /**
         * ReadingHistoryOut
         * @description A past reading as it appears on a profile — it carries its own pick.
         */
        ReadingHistoryOut: {
            /** Pages Read */
            pages_read: number;
            /** Percent */
            percent: number | null;
            /** Rating */
            rating: number | null;
            /** Review */
            review: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            pick: components["schemas"]["MonthlyPickOut"];
        };
        /** UserProfileOut */
        UserProfileOut: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Photo */
            photo: string | null;
            /** Quote */
            quote: string;
            /** Birth Date */
            birth_date: string | null;
            /** Favorites */
            favorites: components["schemas"]["BookOut"][];
            /** Readings */
            readings: components["schemas"]["ReadingHistoryOut"][];
        };
        /** BookIn */
        BookIn: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year?: number | null;
            /** Pages */
            pages?: number | null;
            /**
             * Synopsis
             * @default
             */
            synopsis: string;
            /**
             * Cover Url
             * @default
             */
            cover_url: string;
            /**
             * External Id
             * @default
             */
            external_id: string;
        };
        /**
         * ExternalBookOut
         * @description A hit from the external catalogue, shaped so it can be POSTed back as a BookIn.
         */
        ExternalBookOut: {
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Year */
            year: number | null;
            /** Pages */
            pages: number | null;
            /** Cover Url */
            cover_url: string;
        };
        /**
         * FinishedReaderOut
         * @description One member who finished the current pick and rated it.
         *
         *     It used to be `ReaderOut`, and it used to carry `pages_read`, `percent` and `finished_at`
         *     for a list of everyone with a reading row. The screen behind it now asks a narrower
         *     question — who closed the book, and what did they think — so the fields it stopped
         *     drawing left the contract with it rather than staying on as dead weight.
         *
         *     `rating` is not optional even though the column is: the route filters rows without one
         *     out, so a null can never reach this schema.
         */
        FinishedReaderOut: {
            user: components["schemas"]["UserBrief"];
            /** Rating */
            rating: number;
        };
        /** MonthlyReadingOut */
        MonthlyReadingOut: {
            /** Pages Read */
            pages_read: number;
            /** Percent */
            percent: number | null;
            /** Rating */
            rating: number | null;
            /** Review */
            review: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MonthlyReadingIn */
        MonthlyReadingIn: {
            /** Pages Read */
            pages_read?: number | null;
            /** Rating */
            rating?: number | null;
            /**
             * Clear Rating
             * @default false
             */
            clear_rating: boolean;
            /** Review */
            review?: string | null;
        };
        /** Page */
        Page: {
            /** Items */
            items: components["schemas"]["PostOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Has Next */
            has_next: boolean;
        };
        /** PostOut */
        PostOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            author: components["schemas"]["UserBrief"];
            book: components["schemas"]["BookOut"] | null;
            /** Images */
            images: string[];
        };
        /** PostIn */
        PostIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Book Id */
            book_id?: number | null;
        };
        /**
         * UnreadPostsOut
         * @description How many postagens the member has not seen — see posts.api.unread_posts.
         */
        UnreadPostsOut: {
            /** Count */
            count: number;
        };
        /** PostInPatch */
        PostInPatch: {
            /** Title */
            title?: string | null;
            /** Body */
            body?: string | null;
            /** Book Id */
            book_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    upload_photo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    save_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoritesIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    search_users: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBrief"][];
                };
            };
        };
    };
    read_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
        };
    };
    search_books: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
        };
    };
    create_book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
        };
    };
    search_external_books: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalBookOut"][];
                };
            };
        };
    };
    read_book: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
        };
    };
    list_picks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPickOut"][];
                };
            };
        };
    };
    current_pick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyPickOut"];
                };
            };
        };
    };
    finished_readers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishedReaderOut"][];
                };
            };
        };
    };
    my_reading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReadingOut"];
                };
            };
        };
    };
    update_reading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyReadingIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReadingOut"];
                };
            };
        };
    };
    list_posts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    unread_posts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadPostsOut"];
                };
            };
        };
    };
    mark_posts_seen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadPostsOut"];
                };
            };
        };
    };
    read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
    attach_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
        };
    };
}
