# Generated by Django 5.2.6

from django.db import migrations, models

import core.storage


class Migration(migrations.Migration):
    dependencies = [("posts", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="file",
            field=models.ImageField(upload_to=core.storage.RandomKey("posts/%Y/%m")),
        ),
    ]
