# Generated by Django 5.2.6

from django.db import migrations, models

import core.storage


class Migration(migrations.Migration):
    dependencies = [("books", "0003_review_length_limit")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to=core.storage.RandomKey("covers")),
        ),
    ]
