# Generated by Django 6.0.8 on 2026-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
