# Generated by Django 5.2.6

from django.db import migrations, models

import core.storage


class Migration(migrations.Migration):
    dependencies = [("users", "0003_user_posts_seen_at")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, upload_to=core.storage.RandomKey("profiles")),
        ),
    ]
